Repository 7pandeys/PythonPractice, pull requests merged in 2025-06, with the labels that each got.

#2 Experiment
  notebooks/count_occurances.ipynb
Labels: enhancement, good first issue

#3 Created using Colab
  notebooks/Palindrome.ipynb
Labels: documentation, enhancement, good first issue, wontfix

#4 Revert "Created using Colab"
  notebooks/Palindrome.ipynb
Labels: help wanted, wontfix

#12 Update README
  basics/README.md
Labels: LEARN
